#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BaseLethalEquipment

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function BP_BaseLethalEquipment.BP_BaseLethalEquipment_C.ExecuteUbergraph_BP_BaseLethalEquipment
// 0x008C (0x008C - 0x0000)
struct BP_BaseLethalEquipment_C_ExecuteUbergraph_BP_BaseLethalEquipment final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetRelativeTransform_SweepHitResult;   // 0x0004(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
DUMPER7_ASSERTS_BP_BaseLethalEquipment_C_ExecuteUbergraph_BP_BaseLethalEquipment;

}

