#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CaptureTheFlag_GS

#include "Basic.hpp"

#include "BP_Base_GS_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CaptureTheFlag_GS.BP_CaptureTheFlag_GS_C
// 0x0020 (0x03F0 - 0x03D0)
class ABP_CaptureTheFlag_GS_C final : public ABP_Base_GS_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_CaptureTheFlag_GS_C;             // 0x03D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          NewVar_0_0;                                        // 0x03D8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3D9[0x7];                                      // 0x03D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_BaseFlag_C*                         FlagTeam_1;                                        // 0x03E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_BaseFlag_C*                         FlagTeam_0;                                        // 0x03E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void GetObjectives();
	void ExecuteUbergraph_BP_CaptureTheFlag_GS(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CaptureTheFlag_GS_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CaptureTheFlag_GS_C")
	}
	static class ABP_CaptureTheFlag_GS_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CaptureTheFlag_GS_C>();
	}
};
DUMPER7_ASSERTS_ABP_CaptureTheFlag_GS_C;

}

