#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Glock_17_Weapon

#include "Basic.hpp"

#include "BP_BaseWeapon_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Glock-17_Weapon.BP_Glock-17_Weapon_C
// 0x0000 (0x0460 - 0x0460)
class ABP_Glock_17_Weapon_C final : public ABP_BaseWeapon_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Glock-17_Weapon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Glock-17_Weapon_C")
	}
	static class ABP_Glock_17_Weapon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Glock_17_Weapon_C>();
	}
};
DUMPER7_ASSERTS_ABP_Glock_17_Weapon_C;

}

