#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PickupWeapon

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PickupWeapon.BP_PickupWeapon_C
// 0x0040 (0x0260 - 0x0220)
class ABP_PickupWeapon_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0220(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCapsuleComponent*                      interactionCapsule;                                // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Mesh;                                              // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMesh*                          WeaponMesh;                                        // 0x0238(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	struct FTimerHandle                           CheckVelocityTimerHandle;                          // 0x0240(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x0248(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 WeaponClass;                                       // 0x0250(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	int32                                         Ammo;                                              // 0x0258(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void GetInteractTime(float* InteractTime);
	void GetIcon(class UTexture** Icon);
	void GetDescription(class FText* Description);
	void TryToInteract(bool* bFailure);
	void OnRep_WeaponMesh();
	void BeginInteract(class ACharacter* Instigator_0);
	void EndInteract();
	void StopSimulatingPhysics();
	void EndHover();
	void CheckPhysics();
	void ReceiveBeginPlay();
	void Interact(class ACharacter* Instigator_0);
	void BeginHover(class ACharacter* Instigator_0);
	void ExecuteUbergraph_BP_PickupWeapon(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PickupWeapon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PickupWeapon_C")
	}
	static class ABP_PickupWeapon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PickupWeapon_C>();
	}
};
DUMPER7_ASSERTS_ABP_PickupWeapon_C;

}

