#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SpectatorBase

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_SpectatorBase.BP_SpectatorBase_C.InpAxisEvt_LookUp_K2Node_InputAxisEvent_0
// 0x0004 (0x0004 - 0x0000)
struct BP_SpectatorBase_C_InpAxisEvt_LookUp_K2Node_InputAxisEvent_0 final
{
public:
	float                                         AxisValue;                                         // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_SpectatorBase_C_InpAxisEvt_LookUp_K2Node_InputAxisEvent_0;

// Function BP_SpectatorBase.BP_SpectatorBase_C.InpAxisEvt_Turn_K2Node_InputAxisEvent_1
// 0x0004 (0x0004 - 0x0000)
struct BP_SpectatorBase_C_InpAxisEvt_Turn_K2Node_InputAxisEvent_1 final
{
public:
	float                                         AxisValue;                                         // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_SpectatorBase_C_InpAxisEvt_Turn_K2Node_InputAxisEvent_1;

// Function BP_SpectatorBase.BP_SpectatorBase_C.ExecuteUbergraph_BP_SpectatorBase
// 0x000C (0x000C - 0x0000)
struct BP_SpectatorBase_C_ExecuteUbergraph_BP_SpectatorBase final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_InputAxisEvent_AxisValue_1;                 // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_InputAxisEvent_AxisValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_SpectatorBase_C_ExecuteUbergraph_BP_SpectatorBase;

}

