#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPS_UpdateEnemy

#include "Basic.hpp"

#include "AIModule_structs.hpp"
#include "AIModule_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPS_UpdateEnemy.BPS_UpdateEnemy_C
// 0x0078 (0x0110 - 0x0098)
class UBPS_UpdateEnemy_C final : public UBTService_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0098(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FBlackboardKeySelector                 EnemyKey;                                          // 0x00A0(0x0028)(Edit, BlueprintVisible)
	struct FBlackboardKeySelector                 IsOnSightKey;                                      // 0x00C8(0x0028)(Edit, BlueprintVisible)
	bool                                          bEnemyFound;                                       // 0x00F0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_F1[0x7];                                       // 0x00F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  Pawn;                                              // 0x00F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_BaseCharacter_C*                    Enemy;                                             // 0x0100(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AAIController*                          AI_Controller;                                     // 0x0108(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void IsEnemyAtMeleeRange();
	void IsEnemyOnSight(class AAIController* AIController, bool* bIsOnSight);
	void ReceiveTickAI(class AAIController* OwnerController, class APawn* ControlledPawn, float DeltaSeconds);
	void ExecuteUbergraph_BPS_UpdateEnemy(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPS_UpdateEnemy_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPS_UpdateEnemy_C")
	}
	static class UBPS_UpdateEnemy_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPS_UpdateEnemy_C>();
	}
};
DUMPER7_ASSERTS_UBPS_UpdateEnemy_C;

}

