#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPT_ReturnAlwaysTrue

#include "Basic.hpp"


namespace SDK::Params
{

// Function BPT_ReturnAlwaysTrue.BPT_ReturnAlwaysTrue_C.ReceiveExecuteAI
// 0x0010 (0x0010 - 0x0000)
struct BPT_ReturnAlwaysTrue_C_ReceiveExecuteAI final
{
public:
	class AAIController*                          OwnerController;                                   // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  ControlledPawn;                                    // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPT_ReturnAlwaysTrue_C_ReceiveExecuteAI;

// Function BPT_ReturnAlwaysTrue.BPT_ReturnAlwaysTrue_C.ExecuteUbergraph_BPT_ReturnAlwaysTrue
// 0x0018 (0x0018 - 0x0000)
struct BPT_ReturnAlwaysTrue_C_ExecuteUbergraph_BPT_ReturnAlwaysTrue final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AAIController*                          K2Node_Event_OwnerController;                      // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  K2Node_Event_ControlledPawn;                       // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPT_ReturnAlwaysTrue_C_ExecuteUbergraph_BPT_ReturnAlwaysTrue;

}

