#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DT_BaseDamage

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DT_BaseDamage.DT_BaseDamage_C
// 0x0130 (0x0170 - 0x0040)
class UDT_BaseDamage_C : public UDamageType
{
public:
	class FText                                   WeaponName;                                        // 0x0040(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          bCanHeadshot;                                      // 0x0058(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_59[0x7];                                       // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateBrush                            KillFeedBush;                                      // 0x0060(0x0088)(Edit, BlueprintVisible)
	struct FSlateBrush                            KilledbyBrush;                                     // 0x00E8(0x0088)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DT_BaseDamage_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DT_BaseDamage_C")
	}
	static class UDT_BaseDamage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDT_BaseDamage_C>();
	}
};
DUMPER7_ASSERTS_UDT_BaseDamage_C;

}

