#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DT_M24

#include "Basic.hpp"

#include "DT_BaseDamage_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DT_M24.DT_M24_C
// 0x0000 (0x0170 - 0x0170)
class UDT_M24_C final : public UDT_BaseDamage_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DT_M24_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DT_M24_C")
	}
	static class UDT_M24_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDT_M24_C>();
	}
};
DUMPER7_ASSERTS_UDT_M24_C;

}

