#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DT_Origin_12

#include "Basic.hpp"

#include "DT_BaseDamage_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DT_Origin-12.DT_Origin-12_C
// 0x0000 (0x0170 - 0x0170)
class UDT_Origin_12_C final : public UDT_BaseDamage_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DT_Origin-12_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DT_Origin-12_C")
	}
	static class UDT_Origin_12_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDT_Origin_12_C>();
	}
};
DUMPER7_ASSERTS_UDT_Origin_12_C;

}

