#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DT_ThrowingKnife

#include "Basic.hpp"

#include "DT_BaseDamage_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DT_ThrowingKnife.DT_ThrowingKnife_C
// 0x0000 (0x0170 - 0x0170)
class UDT_ThrowingKnife_C final : public UDT_BaseDamage_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DT_ThrowingKnife_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DT_ThrowingKnife_C")
	}
	static class UDT_ThrowingKnife_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDT_ThrowingKnife_C>();
	}
};
DUMPER7_ASSERTS_UDT_ThrowingKnife_C;

}

