#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FPSSteamGame

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class FPSSteamGame.MyGameModeBase
// 0x0000 (0x02C0 - 0x02C0)
class AMyGameModeBase final : public AGameModeBase
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("MyGameModeBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MyGameModeBase")
	}
	static class AMyGameModeBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMyGameModeBase>();
	}
};
DUMPER7_ASSERTS_AMyGameModeBase;

}

