#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: iPawnActions

#include "Basic.hpp"

#include "iPawnActions_classes.hpp"
#include "iPawnActions_parameters.hpp"


namespace SDK
{

// Function iPawnActions.iPawnActions_C.GetCurrentWeapon
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_BaseWeapon_C**                CurrentWeapon                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IiPawnActions_C::GetCurrentWeapon(class ABP_BaseWeapon_C** CurrentWeapon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "GetCurrentWeapon");

	Params::iPawnActions_C_GetCurrentWeapon Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (CurrentWeapon != nullptr)
		*CurrentWeapon = Parms.CurrentWeapon;
}


// Function iPawnActions.iPawnActions_C.IsAiming
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   bAiming                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void IiPawnActions_C::IsAiming(bool* bAiming)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "IsAiming");

	Params::iPawnActions_C_IsAiming Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (bAiming != nullptr)
		*bAiming = Parms.bAiming;
}


// Function iPawnActions.iPawnActions_C.ShowTPPMesh
// (Public, BlueprintCallable, BlueprintEvent)

void IiPawnActions_C::ShowTPPMesh()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "ShowTPPMesh");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function iPawnActions.iPawnActions_C.HideTPPMesh
// (Public, BlueprintCallable, BlueprintEvent)

void IiPawnActions_C::HideTPPMesh()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "HideTPPMesh");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function iPawnActions.iPawnActions_C.UsingTPP
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   bUsingTPP                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void IiPawnActions_C::UsingTPP(bool* bUsingTPP)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "UsingTPP");

	Params::iPawnActions_C_UsingTPP Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (bUsingTPP != nullptr)
		*bUsingTPP = Parms.bUsingTPP;
}


// Function iPawnActions.iPawnActions_C.AIUseMelee
// (Public, BlueprintCallable, BlueprintEvent)

void IiPawnActions_C::AIUseMelee()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "AIUseMelee");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function iPawnActions.iPawnActions_C.ShowVehicleHitMarker
// (Public, BlueprintCallable, BlueprintEvent)

void IiPawnActions_C::ShowVehicleHitMarker()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "ShowVehicleHitMarker");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function iPawnActions.iPawnActions_C.ShowHitMarker
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsVehicle                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void IiPawnActions_C::ShowHitMarker(bool bIsVehicle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "ShowHitMarker");

	Params::iPawnActions_C_ShowHitMarker Parms{};

	Parms.bIsVehicle = bIsVehicle;

	AsUObject()->ProcessEvent(Func, &Parms);
}


// Function iPawnActions.iPawnActions_C.StopPawn
// (Public, BlueprintCallable, BlueprintEvent)

void IiPawnActions_C::StopPawn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "StopPawn");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function iPawnActions.iPawnActions_C.DestroyPawnWeapon
// (Public, BlueprintCallable, BlueprintEvent)

void IiPawnActions_C::DestroyPawnWeapon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "DestroyPawnWeapon");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function iPawnActions.iPawnActions_C.AddLethalAmmo
// (Public, BlueprintCallable, BlueprintEvent)

void IiPawnActions_C::AddLethalAmmo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "AddLethalAmmo");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function iPawnActions.iPawnActions_C.CharacterNeedsExplosives
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   bNeedsExplosives                                       (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void IiPawnActions_C::CharacterNeedsExplosives(bool* bNeedsExplosives)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "CharacterNeedsExplosives");

	Params::iPawnActions_C_CharacterNeedsExplosives Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (bNeedsExplosives != nullptr)
		*bNeedsExplosives = Parms.bNeedsExplosives;
}


// Function iPawnActions.iPawnActions_C.AddAmmoToCurrentWeapon
// (Public, BlueprintCallable, BlueprintEvent)

void IiPawnActions_C::AddAmmoToCurrentWeapon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "AddAmmoToCurrentWeapon");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function iPawnActions.iPawnActions_C.CharacterdNeedsAmmo
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   bNeedsAmmo                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void IiPawnActions_C::CharacterdNeedsAmmo(bool* bNeedsAmmo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "CharacterdNeedsAmmo");

	Params::iPawnActions_C_CharacterdNeedsAmmo Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (bNeedsAmmo != nullptr)
		*bNeedsAmmo = Parms.bNeedsAmmo;
}


// Function iPawnActions.iPawnActions_C.ThrowItem
// (Public, BlueprintCallable, BlueprintEvent)

void IiPawnActions_C::ThrowItem()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "ThrowItem");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function iPawnActions.iPawnActions_C.IsCharacterFullHP
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   bIsFullHp                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void IiPawnActions_C::IsCharacterFullHP(bool* bIsFullHp)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "IsCharacterFullHP");

	Params::iPawnActions_C_IsCharacterFullHP Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (bIsFullHp != nullptr)
		*bIsFullHp = Parms.bIsFullHp;
}


// Function iPawnActions.iPawnActions_C.StopFiringWeapon
// (Public, BlueprintCallable, BlueprintEvent)

void IiPawnActions_C::StopFiringWeapon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "StopFiringWeapon");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function iPawnActions.iPawnActions_C.SpawnExplosive
// (Public, BlueprintCallable, BlueprintEvent)

void IiPawnActions_C::SpawnExplosive()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "SpawnExplosive");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function iPawnActions.iPawnActions_C.OnWeaponInteract
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_BaseWeapon_C*                 NewWeapon                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IiPawnActions_C::OnWeaponInteract(class ABP_BaseWeapon_C* NewWeapon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "OnWeaponInteract");

	Params::iPawnActions_C_OnWeaponInteract Parms{};

	Parms.NewWeapon = NewWeapon;

	AsUObject()->ProcessEvent(Func, &Parms);
}


// Function iPawnActions.iPawnActions_C.ShowFPPMesh
// (Public, BlueprintCallable, BlueprintEvent)

void IiPawnActions_C::ShowFPPMesh()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "ShowFPPMesh");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function iPawnActions.iPawnActions_C.HideFPPMesh
// (Public, BlueprintCallable, BlueprintEvent)

void IiPawnActions_C::HideFPPMesh()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "HideFPPMesh");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function iPawnActions.iPawnActions_C.OnSuicide
// (Public, BlueprintCallable, BlueprintEvent)

void IiPawnActions_C::OnSuicide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "OnSuicide");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function iPawnActions.iPawnActions_C.FireWeapon
// (Public, BlueprintCallable, BlueprintEvent)

void IiPawnActions_C::FireWeapon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "FireWeapon");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function iPawnActions.iPawnActions_C.OnPickupWeapon
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UClass*                           WeaponClass                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   CurrentAmmo                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IiPawnActions_C::OnPickupWeapon(class UClass* WeaponClass, int32 CurrentAmmo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "OnPickupWeapon");

	Params::iPawnActions_C_OnPickupWeapon Parms{};

	Parms.WeaponClass = WeaponClass;
	Parms.CurrentAmmo = CurrentAmmo;

	AsUObject()->ProcessEvent(Func, &Parms);
}


// Function iPawnActions.iPawnActions_C.AddAmmo
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EAmmoType                               AmmoType                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IiPawnActions_C::AddAmmo(EAmmoType AmmoType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "AddAmmo");

	Params::iPawnActions_C_AddAmmo Parms{};

	Parms.AmmoType = AmmoType;

	AsUObject()->ProcessEvent(Func, &Parms);
}


// Function iPawnActions.iPawnActions_C.OnMeleeCompleted
// (Public, BlueprintCallable, BlueprintEvent)

void IiPawnActions_C::OnMeleeCompleted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "OnMeleeCompleted");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function iPawnActions.iPawnActions_C.OnRefillAmmo
// (Public, BlueprintCallable, BlueprintEvent)

void IiPawnActions_C::OnRefillAmmo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "OnRefillAmmo");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function iPawnActions.iPawnActions_C.OnReloadCompleted
// (Public, BlueprintCallable, BlueprintEvent)

void IiPawnActions_C::OnReloadCompleted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "OnReloadCompleted");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function iPawnActions.iPawnActions_C.IsDead
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   bIsDead                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void IiPawnActions_C::IsDead(bool* bIsDead)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "IsDead");

	Params::iPawnActions_C_IsDead Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (bIsDead != nullptr)
		*bIsDead = Parms.bIsDead;
}


// Function iPawnActions.iPawnActions_C.ShowLethalEquipment
// (Public, BlueprintCallable, BlueprintEvent)

void IiPawnActions_C::ShowLethalEquipment()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "ShowLethalEquipment");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function iPawnActions.iPawnActions_C.HideLethalEquipment
// (Public, BlueprintCallable, BlueprintEvent)

void IiPawnActions_C::HideLethalEquipment()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "HideLethalEquipment");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function iPawnActions.iPawnActions_C.PlayFPPEquipWeapon
// (Public, BlueprintCallable, BlueprintEvent)

void IiPawnActions_C::PlayFPPEquipWeapon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "PlayFPPEquipWeapon");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function iPawnActions.iPawnActions_C.PlayTPPEquipWeapon
// (Public, BlueprintCallable, BlueprintEvent)

void IiPawnActions_C::PlayTPPEquipWeapon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "PlayTPPEquipWeapon");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function iPawnActions.iPawnActions_C.HideWeapon
// (Public, BlueprintCallable, BlueprintEvent)

void IiPawnActions_C::HideWeapon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "HideWeapon");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function iPawnActions.iPawnActions_C.ReduceLethalAmmo
// (Public, BlueprintCallable, BlueprintEvent)

void IiPawnActions_C::ReduceLethalAmmo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "ReduceLethalAmmo");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function iPawnActions.iPawnActions_C.OnPlayerKilled
// (Public, BlueprintCallable, BlueprintEvent)

void IiPawnActions_C::OnPlayerKilled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("iPawnActions_C", "OnPlayerKilled");

	AsUObject()->ProcessEvent(Func, nullptr);
}

}

