#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: iPawnActions

#include "Basic.hpp"

#include "EAmmoType_structs.hpp"


namespace SDK::Params
{

// Function iPawnActions.iPawnActions_C.GetCurrentWeapon
// 0x0008 (0x0008 - 0x0000)
struct iPawnActions_C_GetCurrentWeapon final
{
public:
	class ABP_BaseWeapon_C*                       CurrentWeapon;                                     // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_iPawnActions_C_GetCurrentWeapon;

// Function iPawnActions.iPawnActions_C.IsAiming
// 0x0001 (0x0001 - 0x0000)
struct iPawnActions_C_IsAiming final
{
public:
	bool                                          bAiming;                                           // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_iPawnActions_C_IsAiming;

// Function iPawnActions.iPawnActions_C.UsingTPP
// 0x0001 (0x0001 - 0x0000)
struct iPawnActions_C_UsingTPP final
{
public:
	bool                                          bUsingTPP;                                         // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_iPawnActions_C_UsingTPP;

// Function iPawnActions.iPawnActions_C.ShowHitMarker
// 0x0001 (0x0001 - 0x0000)
struct iPawnActions_C_ShowHitMarker final
{
public:
	bool                                          bIsVehicle;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_iPawnActions_C_ShowHitMarker;

// Function iPawnActions.iPawnActions_C.CharacterNeedsExplosives
// 0x0001 (0x0001 - 0x0000)
struct iPawnActions_C_CharacterNeedsExplosives final
{
public:
	bool                                          bNeedsExplosives;                                  // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_iPawnActions_C_CharacterNeedsExplosives;

// Function iPawnActions.iPawnActions_C.CharacterdNeedsAmmo
// 0x0001 (0x0001 - 0x0000)
struct iPawnActions_C_CharacterdNeedsAmmo final
{
public:
	bool                                          bNeedsAmmo;                                        // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_iPawnActions_C_CharacterdNeedsAmmo;

// Function iPawnActions.iPawnActions_C.IsCharacterFullHP
// 0x0001 (0x0001 - 0x0000)
struct iPawnActions_C_IsCharacterFullHP final
{
public:
	bool                                          bIsFullHp;                                         // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_iPawnActions_C_IsCharacterFullHP;

// Function iPawnActions.iPawnActions_C.OnWeaponInteract
// 0x0008 (0x0008 - 0x0000)
struct iPawnActions_C_OnWeaponInteract final
{
public:
	class ABP_BaseWeapon_C*                       NewWeapon;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_iPawnActions_C_OnWeaponInteract;

// Function iPawnActions.iPawnActions_C.OnPickupWeapon
// 0x0010 (0x0010 - 0x0000)
struct iPawnActions_C_OnPickupWeapon final
{
public:
	class UClass*                                 WeaponClass;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CurrentAmmo;                                       // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_iPawnActions_C_OnPickupWeapon;

// Function iPawnActions.iPawnActions_C.AddAmmo
// 0x0001 (0x0001 - 0x0000)
struct iPawnActions_C_AddAmmo final
{
public:
	EAmmoType                                     AmmoType;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_iPawnActions_C_AddAmmo;

// Function iPawnActions.iPawnActions_C.IsDead
// 0x0001 (0x0001 - 0x0000)
struct iPawnActions_C_IsDead final
{
public:
	bool                                          bIsDead;                                           // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_iPawnActions_C_IsDead;

}

