#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: iUI

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"
#include "EFiringMode_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass iUI.iUI_C
// 0x0000 (0x0000 - 0x0000)
class IiUI_C final
{
public:
	void HideWidget();
	void ShowWidget();
	void ShowAbilityCooldownTime(float TimeRemaining);
	void HideInteractInfo();
	void ShowInteractInfo(const class FText& Description);
	void ShowHealOverlay();
	void HideInteractProgressBar();
	void ShowInteractProgressBar(float InteractTime);
	void UpdateObjectiveMarkers(class ABP_Base_Objective_C* ObjectiveToUpdate, bool PlayIconAnim, int32 Team);
	void HideWeaponInfo();
	void ShowScore(float Score, const class FText& Reason);
	void UpdateKillFeed(class APlayerState* Killer, class APlayerState* Victim, const class UDamageType* DamageType, class APlayerState* Assist, bool bHeadshot);
	void UpdateGameModeScores(int32 TeamAPoints, int32 TeamBPoints, int32 PointsToWin);
	void UpdateMatchTimer(float TimeInSeconds);
	void ShowHitOverlay();
	void UpdateTotalBullets(int32 TotalBullets);
	void UpdateCurrentBullets(int32 CurrentBullets, int32 BulletsPerMag);
	void UpdateHP(float NewHP, float MaxHP);
	void UpdateFiringMode(EFiringMode NewFiringMode);
	void ShowKillMarker();
	void ShowHitMarker(bool bVehicle);
	void OnOwnerDeath();
	void UpdateExplosives(int32 ExplosivesAmount, class UTexture* Icon);
	void UpdateRushScores(int32 Reinforcements, int32 TotalReinforcements);
	void UpdateDeathmatchScores(const class FString& WinnerName, int32 WinnerKills, int32 KillsToWin);
	void UpdateTeamIcon(class UTexture* TeamIcon);
	void ShowCrouchIcon();
	void ShowStandingIcon();
	void UpdateSkillIcon(class UTexture2D* SkillIcon);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("iUI_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"iUI_C")
	}
	static class IiUI_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IiUI_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IiUI_C;

}

