#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_ChatText

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WB_ChatText.WB_ChatText_C
// 0x0050 (0x02B0 - 0x0260)
class UWB_ChatText_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UTextBlock*                             MessageWidget;                                     // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   ActualTest;                                        // 0x0270(0x0018)(Edit, BlueprintVisible, Net, ExposeOnSpawn)
	bool                                          bTeamChat;                                         // 0x0288(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	bool                                          bServerMessage;                                    // 0x0289(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	uint8                                         Pad_28A[0x2];                                      // 0x028A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           DefautlFontColor;                                  // 0x028C(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           TeamChatFontColor;                                 // 0x029C(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	struct FSlateColor GetTextColor();
	void Construct();
	void ExecuteUbergraph_WB_ChatText(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WB_ChatText_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WB_ChatText_C")
	}
	static class UWB_ChatText_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_ChatText_C>();
	}
};
DUMPER7_ASSERTS_UWB_ChatText_C;

}

