#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_ClaymoreFailmessage

#include "Basic.hpp"


namespace SDK::Params
{

// Function WB_ClaymoreFailmessage.WB_ClaymoreFailmessage_C.ExecuteUbergraph_WB_ClaymoreFailmessage
// 0x0010 (0x0010 - 0x0000)
struct WB_ClaymoreFailmessage_C_ExecuteUbergraph_WB_ClaymoreFailmessage final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetEndTime_ReturnValue;                   // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WB_ClaymoreFailmessage_C_ExecuteUbergraph_WB_ClaymoreFailmessage;

}

