#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_CaptureTheFlag_UI_Icon

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WB_CaptureTheFlag_UI_Icon.WB_CaptureTheFlag_UI_Icon_C
// 0x0018 (0x0278 - 0x0260)
class UWB_CaptureTheFlag_UI_Icon_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       FadeInAnim;                                        // 0x0268(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 FlagIcon;                                          // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void Construct();
	void RemoveWidget();
	void ExecuteUbergraph_WB_CaptureTheFlag_UI_Icon(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WB_CaptureTheFlag_UI_Icon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WB_CaptureTheFlag_UI_Icon_C")
	}
	static class UWB_CaptureTheFlag_UI_Icon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_CaptureTheFlag_UI_Icon_C>();
	}
};
DUMPER7_ASSERTS_UWB_CaptureTheFlag_UI_Icon_C;

}

