#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_ConquestObjective

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function WB_ConquestObjective.WB_ConquestObjective_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WB_ConquestObjective_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WB_ConquestObjective_C_PreConstruct;

// Function WB_ConquestObjective.WB_ConquestObjective_C.UpdatePercent
// 0x0004 (0x0004 - 0x0000)
struct WB_ConquestObjective_C_UpdatePercent final
{
public:
	float                                         Percent_0;                                         // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WB_ConquestObjective_C_UpdatePercent;

// Function WB_ConquestObjective.WB_ConquestObjective_C.UpdateColor
// 0x0010 (0x0010 - 0x0000)
struct WB_ConquestObjective_C_UpdateColor final
{
public:
	struct FLinearColor                           Color_0;                                           // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WB_ConquestObjective_C_UpdateColor;

// Function WB_ConquestObjective.WB_ConquestObjective_C.UpdateTextColor
// 0x0010 (0x0010 - 0x0000)
struct WB_ConquestObjective_C_UpdateTextColor final
{
public:
	struct FLinearColor                           Color_0;                                           // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WB_ConquestObjective_C_UpdateTextColor;

// Function WB_ConquestObjective.WB_ConquestObjective_C.ExecuteUbergraph_WB_ConquestObjective
// 0x0060 (0x0060 - 0x0000)
struct WB_ConquestObjective_C_ExecuteUbergraph_WB_ConquestObjective final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_CustomEvent_Percent;                        // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue;           // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           K2Node_CustomEvent_Color_1;                        // 0x0018(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           K2Node_CustomEvent_Color;                          // 0x0028(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0038(0x0028)()
};
DUMPER7_ASSERTS_WB_ConquestObjective_C_ExecuteUbergraph_WB_ConquestObjective;

}

