#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_CapturePointIcon1

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ECapturePointState_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WB_CapturePointIcon1.WB_CapturePointIcon1_C
// 0x0038 (0x0298 - 0x0260)
class UWB_CapturePointIcon1_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       IconAnimation;                                     // 0x0268(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UButton*                                Button_46;                                         // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             DistanceText;                                      // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Icon;                                              // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FVector                                ObjetiveLocation;                                  // 0x0288(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	class FText GetPlayerDistance();
	void StopPlayingAnimation();
	void Construct();
	void Update_Distance();
	void StartPlayingAnimation();
	void Set_Icon(class UTexture2D* Icon_0);
	void SetIconColor(ECapturePointState Team);
	void BndEvt__WB_CapturePointIcon1_Button_46_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void ExecuteUbergraph_WB_CapturePointIcon1(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WB_CapturePointIcon1_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WB_CapturePointIcon1_C")
	}
	static class UWB_CapturePointIcon1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_CapturePointIcon1_C>();
	}
};
DUMPER7_ASSERTS_UWB_CapturePointIcon1_C;

}

