#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_CookingGrenade

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WB_CookingGrenade.WB_CookingGrenade_C
// 0x0018 (0x0278 - 0x0260)
class UWB_CookingGrenade_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       CookGrenade;                                       // 0x0268(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 CookingGrenadeCrosshair;                           // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void Construct();
	void RemoveWidget();
	void ExecuteUbergraph_WB_CookingGrenade(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WB_CookingGrenade_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WB_CookingGrenade_C")
	}
	static class UWB_CookingGrenade_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_CookingGrenade_C>();
	}
};
DUMPER7_ASSERTS_UWB_CookingGrenade_C;

}

