#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_Chat

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WB_Chat.WB_Chat_C
// 0x0008 (0x0268 - 0x0260)
class UWB_Chat_C final : public UUserWidget
{
public:
	class UWB_ChatWindow_C*                       ChatWindow;                                        // 0x0260(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WB_Chat_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WB_Chat_C")
	}
	static class UWB_Chat_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_Chat_C>();
	}
};
DUMPER7_ASSERTS_UWB_Chat_C;

}

