#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_PatchNotesParent

#include "Basic.hpp"


namespace SDK::Params
{

// Function WB_PatchNotesParent.WB_PatchNotesParent_C.ExecuteUbergraph_WB_PatchNotesParent
// 0x0004 (0x0004 - 0x0000)
struct WB_PatchNotesParent_C_ExecuteUbergraph_WB_PatchNotesParent final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WB_PatchNotesParent_C_ExecuteUbergraph_WB_PatchNotesParent;

}

